environment:
  matrix:
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe -m pip install pip -U"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt -U"
  - "%PYTHON%\\python.exe -m pip install -e ."

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest"

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/c084306bedf9aa508af2
    method: GET
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
